<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
		
		<!-- Nuget Tags -->
		<AssemblyTitle>Godot Remote Tree Inspector</AssemblyTitle>
		<Description>A UI Element that allows you to inspect the SceneTree of a running Godot application.</Description>
		<PackageTags>godot;scenetree;remote;debug;debugging</PackageTags>
		<Authors>Mario Steele</Authors>
		<RepositoryUrl>https://github.com/eumario/GodotSharpRemoteTree</RepositoryUrl>
		<Copyright>Copyright (c) 2026 Mario Steele</Copyright>
		<PackageReleaseNotes>Initial Release</PackageReleaseNotes>
		<PackageReadmeFile>README.md</PackageReadmeFile>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Godot.SourceGenerators" Version="4.6.0" />
      <PackageReference Include="GodotSharp" Version="4.6.0" />
      <PackageReference Include="GodotSharpEditor" Version="4.6.0" />
    </ItemGroup>
    
    <ItemGroup>
        <EmbeddedResource Label="remote_debugger_tree.res" Include="remote_debugger_tree.res" />
    </ItemGroup>

</Project>
